### PR TITLE
emit finish for writestream

### PR DESCRIPTION
**Pull request by martingg88**
add this to ensure it release underlying operation and it turn we can manipulate the file later one.

### CODE REVIEW

**Comment by zenflow** [comment]
`self` shouldn't emit a `'finish'` event since FastDownload inherits stream.Readable, not stream.Writable. See the listed events in nodejs documentation for [stream.Readable](https://nodejs.org/api/stream.html#stream_class_stream_readable). You probably want to be listening for the `'end'` event instead.

Did that help resolve your problem?

**Comment by martingg88** [comment]
opsss. i did this because fs.stats may not return accurate file size in end event which has not yet close underlying operation. besides that, i think i should emit finish for Writable stream and emit close for Readable stream. i will re-submit the pull request. thanks.

**Comment by martingg88** [comment]
updated finish to close event for readable stream. check this out. thanks.

**Comment by zenflow** [comment]
I'm closing this PR for a number of reasons:

- The file write stream should only emit 'finish' once the download emits 'end', so forcing the download to emit 'end' after the file write stream emits 'finish' is not only redundant, but would cause unexpected behavior. It would emit 'end' twice, where it should only emit 'end' once. 

- Besides that, all this PR adds is counting the number of requests ended and logging that number to the console. This is undesirable for almost everyone using this module.

**Pull request closed without merging**
